### ISSUE TITLE
NOT a real issue some help

### ISSUE THREAD

**Issue by SmokiinTreez** [kamikazechaser/zcash-mining#2]
How can i check my wallet ? t_listaddresses ? and make etc ?

Thanks in advance

**Comment by kamikazechaser** [comment]
There is a nice Java GUI, Ill link you to it.

**Comment by nadroj71** [comment]
Would you mind linking me to it also?

**Comment by kamikazechaser** [comment]
https://github.com/vaklinov/zcash-swing-wallet-ui

**Comment by kamikazechaser** [comment]
An alternative: https://coinreport.net/blockchain-wallet-jaxx-integrates-zcash/
